### ISSUE TITLE
توسعه افزونه مرورگر رستم بات

### ISSUE THREAD

**Issue by thebrodmann** [Hameds/RostamBot#19]
<div dir="rtl">
این
issue
را به دلیل دعوت از برنامه نویسان علاقه مند به مشارکت در افزونه مرورگر رستم بات باز کردم.

در حال حاظر افزونه مرورگر رستم بات در مخزن  <a href="https://github.com/thebrodmann/rostam-bot-extension">thebrodmann/rostam-bot-extension</a> در حال توسعه است.

@Hameds عزیز, اگر ممکن هست تا زمانی که مستندات کافی فراهم بشه اجازه بدید این issue باز باشه.
</div>

**Comment by Hameds** [comment]
<div dir="rtl">

@thebrodmann با تکمیل #24  آدرس API ها تمیز شدند و حالا برای استفاده در افزونه مرورگر آماده‌اند، البته تا پیش از رلیز نهایی افزونه مرورگر باید مشکل کش #20  هم حل شود

</div>
