### ISSUE TITLE
تمیز کردن آدرس‌های API

### ISSUE THREAD

**Issue by Hameds** [Hameds/RostamBot#24]
<div dir="rtl">

پیرو این توییت‌ها [https://twitter.com/khos2ow/status/1166391145112449024](https://twitter.com/khos2ow/status/1166391145112449024)

> یه پیشنهادی که فقط با دیدن اون اسکرین‌شات بالا دارم اینه که اندپوینت‌های api خیلی تمیز نیست. به نظر من بهتره که همه اندپوینت ها زیر /api/v1 برن. اساس کار این ربات روی Suspicious اکتیویتی‌ه، دیگه احتیاجی نیست همون کلمه suspicious توی آدرس باشه
لیست GetTwitterBlockedList خیلی redundantه، مخصوصا که روی GET داره جواب می‌ده و می‌تونه باشه
GET /api/v1/twitter/list
و به همین ترتیب برای بقیه ای‌پی‌آی‌ها. و نکته آخر اینکه همه اندپوینت‌ها به حروف کوچیک باشن.

</div>

**Comment by khos2ow** [comment]
+1

**Comment by thebrodmann** [comment]
<div dir="rtl">
حالا که endpoint های فعلی رفتن زیر v1 یعنی که breaking change قرار نیست دیگه روی endpoint های فعلی رخ بده؟
</div>

**Comment by Hameds** [comment]
<div dir="rtl">

@thebrodmann ممنون به خاطر دقت نظرت. بلی در v1 قرار نیست breaking change داشته باشیم. احتمالاً در طول توسعه فعلی تنها یک متد به این API اضافه بشه، بنابراین فعلاً صرفنظر از milestone این رو می‌شه نسخه 1 در نظر گرفت. همچنین در طول توسعه، بنا به پیشنهاد درست در #20  تغییراتی در زیرساخت داده می‌شه اما خروجی و نام توابع API ثابت خواهد موند

</div>
